spring:
  profiles: dev
custom:
  message: Hello, api-dev!
---
spring:
  profiles: stg
server:
  port: 9999
custom:
  message: Hello, api stg!
---
spring:
  profiles: prd
custom:
  message: Hello, api prd!