spring:
  profiles:
    active: dev
  application:
    name: api
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      uri: http://localhost:8888

---
spring:
  config:
    activate:
      on-profile: stg
  cloud:
    config:
      uri: http://stgapi.yeop.com
---
spring:
  config:
    activate:
      on-profile: prd
  cloud:
    config:
      uri: http://api.yeop.com
